export const GET_FLASH_CARDS_SUCCESS = 'GET_FLASH_CARDS_SUCCESS'
export const GET_FLASH_CARDS_FAILURE = 'GET_FLASH_CARDS_FAILURE'
export const ADD_NEW_DECK_SUCCESS = 'ADD_NEW_DECK_SUCCESS'
export const ADD_NEW_DECK_FAILURE = 'ADD_NEW_DECK_FAILURE'
